version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: "1MQh41gK#>"
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube-db:/var/lib/postgresql
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - sonar-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar -d sonarqube"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: "1MQh41gK#>"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    ports:
      - "55000:9000"
    restart: unless-stopped
    networks:
      - sonar-net

volumes:
  sonarqube-data:
    external: true
  sonarqube-extensions:
    external: true
  sonarqube-logs:
    external: true
  sonarqube-db:
    external: true
  sonarqube-db-data:
    external: true

networks:
  sonar-net:
    driver: bridge
    